### ISSUE TITLE
Bug: crash while reporting crash

### ISSUE THREAD

**Issue by AbsurdUsername** [sunilpaulmathew/Translator#31]
- First bug: I was just translating and typoed pressed save and crashed(no way the app knows how many characters it'll be), crash report:
 
`java.lang.ArrayIndexOutOfBoundsException: length=33; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at t1.e.onClick(:3)
	at androidx.appcompat.app.AlertController$c.handleMessage(Unknown Source:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

- Second bug: press report in the crash section, send it somewhere and press cancel. Crash report:

`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.io.Writer.write(Writer.java:157)
	at z1.j.a(Unknown Source:5)
	at z1.a.a(:4)
	at in.sunilpaulmathew.sCommon.Activities.sCrashReporterActivity.onBackPressed(Unknown Source:0)
	at x1.a.onClick(:3)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28312)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by sunilpaulmathew** [comment]
@AbsurdUsername 
Thanks. The first one rarely happened. I'll look for it. And the second: basically harmless (except destroying the original crash report)

**Comment by AbsurdUsername** [comment]
I've been using it more and the first bug keeps showing. Doesn't seem rare, and makes it quite difficult to use the app

**Comment by sunilpaulmathew** [comment]
> I've been using it more and the first bug keeps showing. Doesn't seem rare, and makes it quite difficult to use the app
> 
> Edit: I'm on android 11, custom rom

Then, I'll have to seriously look on it.  Haven't been used it for a while.

**Comment by AbsurdUsername** [comment]
Also while we're at it, I noticed the app puts every string between quotes, like:
`<string name="example">**"**this is an example string**"**</string>`

**Comment by sunilpaulmathew** [comment]
> Also while we're at it, I noticed the app puts every string between quotes, like:
> 
> `<string name="example">"this is an example string"</string>`

Which is intentional. It will help us to handle a lot of special characters much easily.

**Comment by AbsurdUsername** [comment]
Oh got it. Maybe a switch to turn it on/off would be nice

**Comment by sunilpaulmathew** [comment]
Not really required as these quotes doesn't make any issues. Moreover, disabling it will necessitates additional work to check illegal characters.
