### ISSUE TITLE
Crash The Translator

### ISSUE THREAD

**Issue by Shopimisrel** [sunilpaulmathew/Translator#37]
App Name: The Translator
Package Name: com.sunilpaulmathew.translator
App Version: v0.17
SDK Version: 29

Crash Report

java.lang.ArrayIndexOutOfBoundsException: length=366; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at t1.e.onClick(:3)
	at androidx.appcompat.app.AlertController$c.handleMessage(Unknown Source:37)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7389)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Steps to reproduce the issue:

**Comment by sunilpaulmathew** [comment]
@Shopimisrel 
I hope this issue is fixed as of v0.18. So, closing this issue. If not, please feel free to reopen this.
